import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import test from 'node:test'
import { Schema } from '@tiptap/pm/model'
import { registerKnowledgeWeb } from '../lib/web.js'
import { plainTextFromDocument, plainTextToDocument } from '../lib/web-note-editor.js'
import { findNoteSearchRanges } from '../lib/web-note-editor-search.js'
import { calculateHeadingScrollTop } from '../lib/web-note-editor-outline.js'

test('plain text note documents preserve logical lines exactly', () => {
  const source = '第一行\n会自动折行但仍是一行的长内容\n\n最后一行\n'
  assert.equal(plainTextFromDocument(plainTextToDocument(source)), source)
})

test('note search finds literal text across inline formatting without regex surprises', () => {
  const schema = new Schema({
    nodes: {
      doc: { content: 'paragraph+' },
      paragraph: { content: 'inline*', group: 'block' },
      text: { group: 'inline' },
      hard_break: { inline: true, group: 'inline' },
    },
    marks: { strong: {} },
  })
  const strong = schema.marks.strong.create()
  const document = schema.node('doc', null, [
    schema.node('paragraph', null, [schema.text('Doc'), schema.text('most', [strong]), schema.text(' docmost.')]),
  ])
  assert.deepEqual(findNoteSearchRanges(document, 'docmost', false), [
    { from: 1, to: 8 },
    { from: 9, to: 16 },
  ])
  assert.deepEqual(findNoteSearchRanges(document, '.', true), [{ from: 16, to: 17 }])
  const broken = schema.node('doc', null, [schema.node('paragraph', null, [
    schema.text('Doc'), schema.node('hard_break'), schema.text('most'),
  ])])
  assert.deepEqual(findNoteSearchRanges(broken, 'docmost', false), [])
  assert.deepEqual(findNoteSearchRanges(broken, 'most', false), [{ from: 5, to: 9 }])
})

test('outline heading navigation stays within the document scroll range', () => {
  assert.equal(calculateHeadingScrollTop(120, 480, 80, 900), 504)
  assert.equal(calculateHeadingScrollTop(20, 75, 80, 900), 0)
  assert.equal(calculateHeadingScrollTop(860, 300, 80, 900), 900)
  assert.equal(calculateHeadingScrollTop(120, 480, 80, -20), 0)
})

test('management console serves a secured same-origin application', async (t) => {
  let route
  const ctx = {
    webServer: {
      register(value) {
        route = value
        return () => { route = undefined }
      },
    },
    get() { return undefined },
  }
  const dispose = registerKnowledgeWeb(ctx, '/knowledge', '/knowledge-local/v1', 'same-origin', 'desktop-embed-token')
  assert.equal(route.kind, 'prefix')
  assert.equal(route.path, '/knowledge')
  const server = createServer((req, res) => void route.handler(req, res))
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const address = server.address()
  const base = `http://127.0.0.1:${address.port}`
  t.after(async () => {
    dispose()
    await new Promise(resolve => server.close(resolve))
  })

  const index = await fetch(`${base}/knowledge`)
  assert.equal(index.status, 200)
  assert.equal(index.headers.get('x-frame-options'), 'SAMEORIGIN')
  assert.match(index.headers.get('content-security-policy'), /frame-ancestors 'self'/)
  assert.match(index.headers.get('content-security-policy'), /img-src 'self' data: blob:/)
  assert.match(index.headers.get('content-security-policy'), /frame-src blob:/)
  assert.match(index.headers.get('content-security-policy'), /style-src 'self' 'sha256-[^']+'; style-src-attr 'unsafe-inline'/)
  const html = await index.text()
  assert.match(html, /name="dsh-knowledge-api" content="\/knowledge-local\/v1"/)
  assert.match(html, /name="dsh-knowledge-auth-mode" content="same-origin"/)
  assert.match(html, /src="\/knowledge\/app\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /src="\/knowledge\/change-review\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /src="\/knowledge\/markdown-preview\.js\?v=[a-f0-9]{12}"/)
  assert.doesNotMatch(html, /workspace-effects\.js/)
  assert.match(html, /name="dsh-knowledge-asset-version" content="[a-f0-9]{12}"/)
  assert.match(html, /href="\/knowledge\/styles\.css\?v=[a-f0-9]{12}"/)
  assert.equal(index.headers.get('cache-control'), 'no-store')

  const script = await fetch(`${base}/knowledge/app.js`)
  assert.equal(script.status, 200)
  assert.match(script.headers.get('content-type'), /text\/javascript/)
  assert.equal(script.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  const application = await script.text() + '\n' + await (await fetch(`${base}/knowledge/dialogs.js`)).text()
    + '\n' + await (await fetch(`${base}/knowledge/document-actions.js`)).text()
  assert.match(application, /sessionStorage/)
  assert.match(application, /document-index/)
  assert.doesNotMatch(application, /api\('documents'\)/)
  assert.match(application, /note-workspace/)
  assert.match(application, /note-tree-panel/)
  assert.match(application, /note-tree-base/)
  assert.match(application, /note-tree-document/)
  assert.doesNotMatch(application, /data-knowledge-motion-key/)
  assert.match(application, /data-document-id/)
  assert.doesNotMatch(application, /DshKnowledgeEffects|refreshWorkspaceEffects/)
  assert.match(application, /note-editor/)
  assert.match(application, /note-title-input/)
  assert.match(application, /knowledge-live-editor/)
  assert.match(application, /DshKnowledgeMarkdown\.renderMarkdown/)
  assert.match(application, /markdown-table-scroll/)
  assert.match(application, /таблиц/)
  assert.match(application, /loadMarkdownNoteEditor/)
  assert.match(application, /DshKnowledgeNoteEditor/)
  assert.match(application, /data-note-find/)
  assert.match(application, /data-note-outline/)
  assert.match(application, /data-note-history/)
  assert.match(application, /function openNoteHistory/)
  assert.match(application, /aria-keyshortcuts': 'Control\+F Meta\+F'/)
  assert.match(application, /notes-editor-frame/)
  assert.match(application, /createPlainTextEditor/)
  assert.match(application, /createApiClient/)
  assert.match(application, /function collectNoteEntry\(/)
  assert.match(application, /function importNotePlans\(/)
  assert.doesNotMatch(application, /DshKnowledgePlainTextEditor|plain-text-editor\.js/)
  assert.doesNotMatch(application, /function switchDocumentMode\(/)
  const editableNoteSource = application.slice(application.indexOf('function renderEditableNote('), application.indexOf('function renderNoteDocumentBreadcrumb('))
  assert.doesNotMatch(editableNoteSource, /note-mode-switch|预览.*编辑|renderMarkdownPreview/)
  assert.doesNotMatch(editableNoteSource, /notes-document-paper|notes-document-editor|textarea/)
  assert.match(editableNoteSource, /notes-document-title/)
  assert.match(editableNoteSource, /spellcheck: 'false'/)
  assert.match(editableNoteSource, /has-line-numbers/)
  assert.match(editableNoteSource, /notes-plain-editor/)
  assert.match(editableNoteSource, /mountPlainTextNoteEditor/)
  assert.doesNotMatch(editableNoteSource, /class: 'notes-plain-editor', contenteditable/)
  assert.match(editableNoteSource, /saveEditableNoteTitle/)
  assert.match(editableNoteSource, /body: \{ name, expectedName: node.name \}/)
  assert.match(application, /data-tree-open/)
  assert.match(application, /note-tree-scrim/)
  assert.match(application, /saveDocumentEditor/)
  assert.match(application, /createBlankDocument/)
  assert.match(application, /function documentKnowledgeBases/)
  assert.match(application, /function openKnowledgeBaseDocuments/)
  assert.match(application, /function renderKnowledgeBaseDetail/)
  assert.match(application, /params\.append\('knowledgeBaseId'/)
  assert.match(application, /libraryDetail/)
  assert.doesNotMatch(application, /inspectedKnowledgeBaseId/)
  assert.match(application, /mounts\/resolve/)
  assert.match(application, /К сессии не подключено/)
  assert.match(application, /confirmDeleteDocument/)
  assert.match(application, /openFinalizeDocument/)
  assert.match(application, /reopenDocument/)
  assert.match(application, /已收集完成/)
  assert.match(application, /editor-save-status/)
  assert.doesNotMatch(application, /renderDocumentModeTabs|renderLegacyEntries/)
  assert.match(application, /app-sidebar-resizer/)
  assert.doesNotMatch(application, /视图设置|openLayoutEditor|layoutRangeField/)
  assert.match(application, /pane-toggle-button/)
  assert.match(application, /aria-pressed/)
  assert.match(application, /function renderContextPaneToggle\(\)/)
  assert.match(application, /state\.notes\.browserOpen/)
  assert.match(application, /data-browser-open/)
  assert.match(application, /notes-browser-scrim/)
  assert.match(application, /workspace-switcher/)
  assert.match(application, /knowledgeBaseQuery/)
  assert.match(application, /function renderNotes\(\)/)
  assert.match(application, /function openNoteAgentGuide\(\)/)
  assert.match(application, /className: 'notes-agent-guide-dialog'/)
  assert.match(application, /function renderShares\(\)/)
  assert.match(application, /function openImportNoteShare\(\)/)
  assert.match(application, /notes\/import-share\/inspect/)
  assert.doesNotMatch(application, /function renderNoteWorkspaceTabs\(\)|function setNoteSection\(/)
  assert.match(application, /function showNoteShareDialog\(share\)/)
  assert.match(application, /notes\/\$\{encodeURIComponent\(node\.id\)\}\/share/)
  assert.match(application, /已分享/)
  assert.match(application, /会话指令/)
  assert.match(application, /当前消息里指定笔记文档/)
  assert.match(application, /发布资料\/上线检查\.md/)
  assert.match(application, /function noteDownloadButton\(node/)
  assert.match(application, /下载失败：/)
  assert.match(application, /function renderNoteFileStatusbar\(node\)/)
  const noteToolbarSource = application.slice(application.indexOf('function renderNoteFileToolbar('), application.indexOf('function renderNoteFileStatusbar('))
  assert.doesNotMatch(noteToolbarSource, /noteInfoItem\(/)
  const noteStatusbarSource = application.slice(application.indexOf('function renderNoteFileStatusbar('), application.indexOf('function noteInfoItem('))
  assert.match(noteStatusbarSource, /noteInfoItem\('编号'/)
  assert.match(noteStatusbarSource, /noteInfoItem\('更新'/)
  assert.match(application, /function loadDocumentPage/)
  assert.match(application, /function loadDocumentSearch/)
  assert.match(application, /继续加载/)
  assert.match(application, /function uploadNoteFiles\(files, parentId\)/)
  assert.match(application, /function importDroppedNotes\(dataTransfer, parentId\)/)
  assert.match(application, /function readNoteDirectoryEntries\(entry\)/)
  assert.match(application, /webkitGetAsEntry/)
  assert.match(application, /function openDocumentNoteReferencePicker/)
  assert.match(application, /function renderDocumentReferenceBar/)
  assert.match(application, /document-reference-bar/)
  assert.match(application, /entries\/\$\{encodeURIComponent\(editor\.id\)\}\/note-references/)
  const knowledgeEditorSource = application.slice(application.indexOf('function renderNoteEditor('), application.indexOf('function renderMarkdownPreview('))
  assert.doesNotMatch(knowledgeEditorSource, /insertMarkdown\(reference\)|@ 引用笔记/)
  assert.match(application, /function clearNoteDragState/)
  assert.match(application, /function installDragRecovery/)
  assert.doesNotMatch(application, /dataTransfer\.types\.includes/)
  assert.match(application, /note:\/\//)
  assert.match(application, /复制引用/)
  assert.match(application, /function renderNoteFileToolbar\(node, options = \{\}\)/)
  assert.match(application, /function renderNoteFileOverflowMenu\(node, options\)/)
  assert.match(application, /function createDocumentMenuPresenter/)
  assert.match(application, /interfaceIcon\('more', 'notes-document-more-icon'\)/)
  assert.match(application, /interfaceIcon\('outline', 'notes-toolbar-action-icon'\)/)
  assert.doesNotMatch(application, /noteMenuAction\('标题大纲', 'outline'/)
  assert.doesNotMatch(application, /data-note-mobile-overflow/)
  assert.match(application, /notes-document-more-menu/)
  assert.match(application, /node\.editable/)
  assert.match(application, /function releaseNoteAsset\(\)/)
  assert.doesNotMatch(application, /openNoteFilePreview/)
  assert.match(application, /writebackPolicy/)
  assert.match(application, /openGlobalWritebackModelEditor/)
  assert.match(application, /严谨/)
  assert.match(application, /主动/)
  assert.match(application, /loading-skeleton/)
  assert.match(application, /function renderCandidateDiff/)
  assert.match(application, /function openBulkApprove/)
  assert.match(application, /candidates\/bulk-review/)
  assert.match(application, /一键通过/)
  assert.match(application, /function renderDiffLine/)
  assert.match(application, /DshKnowledgeReview\.createReviewChange/)
  assert.match(application, /写入新文档/)
  assert.match(application, /补充到文档/)
  assert.match(application, /应用修订/)
  assert.match(application, /原文修订预览/)
  assert.match(application, /data-sidebar-hidden/)
  assert.match(application, /function applySidebarVisibility\(shell, hidden\)/)
  assert.match(application, /const sidebarUnavailable = compact \? !state\.menuOpen : hidden/)
  assert.match(application, /sidebar\?\.toggleAttribute\('inert', sidebarUnavailable\)/)
  assert.match(application, /main\?\.toggleAttribute\('inert', compact && state\.menuOpen\)/)
  assert.match(application, /class: 'app-sidebar-scrim'/)
  assert.match(application, /toggle\.setAttribute\('aria-pressed', String\(visible\)\)/)
  const sidebarToggleSource = application.slice(application.indexOf('function setSidebarHidden('), application.indexOf('function renderSidebar('))
  assert.doesNotMatch(sidebarToggleSource, /renderShell\(\)/)
  assert.match(application, /永久删除/)
  assert.match(application, /输入知识库名称确认/)
  assert.match(await (await fetch(`${base}/knowledge/model-catalog.js`)).text(), /x-dsh-knowledge-client/)
  assert.match(application, /远程知识库 API/)
  assert.match(application, /复制地址/)
  assert.match(application, /开启远程 API/)
  assert.match(application, /已撤销令牌已永久删除/)
  assert.match(application, /captureScrollPosition/)
  assert.match(application, /restoreScrollPosition/)
  assert.match(application, /data-scroll-key/)
  assert.match(application, /import\(moduleUrl\('host-theme'\)\)/)
  assert.match(application, /installHostThemeBridge\(\)\.then\(\(\) => boot\(\)\)/)

  const hostThemeResponse = await fetch(`${base}/knowledge/host-theme.js`)
  assert.equal(hostThemeResponse.status, 200)
  const hostTheme = await hostThemeResponse.text()
  assert.match(hostTheme, /host-theme-ready/)
  assert.match(hostTheme, /event\.source !== window\.parent/)
  assert.match(hostTheme, /parentOrigin && event\.origin !== parentOrigin/)
  assert.match(hostTheme, /CSS\.supports\('color'/)
  assert.match(hostTheme, /root\.style\.colorScheme/)
  assert.match(hostTheme, /root\.dataset\.colorScheme/)

  const effectsScript = await fetch(`${base}/knowledge/workspace-effects.js`)
  assert.equal(effectsScript.status, 404)

  const stylesheet = await fetch(`${base}/knowledge/styles.css`)
  assert.equal(stylesheet.status, 200)
  const styles = await stylesheet.text()
  assert.match(styles, /\.notes-agent-guide-rule/)
  assert.match(styles, /\.notes-agent-capabilities/)
  assert.match(styles, /data-sidebar-hidden="true"/)
  assert.match(styles, /\.app-sidebar-scrim \{ position: fixed; inset: 0; z-index: 30; display: block;/)
  assert.match(styles, /\.sidebar \{\s*position: fixed;[^}]*z-index: 40;/)
  assert.doesNotMatch(styles, /data-menu-open="true"\]::after/)
  assert.match(styles, /\.note-workspace/)
  assert.match(styles, /\.note-tree-panel \{[\s\S]*min-height: 0;[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.note-tree \{[\s\S]*overflow-y: auto;/)
  assert.match(styles, /\.note-editor \{[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.note-editor-toolbar \{[\s\S]*z-index: 2;[\s\S]*background: transparent;[\s\S]*backdrop-filter: none;/)
  assert.match(styles, /\.note-editor-scroll \{[\s\S]*overflow: auto;[\s\S]*overscroll-behavior: contain;/)
  assert.match(styles, /\.tree-folder-icon \{[\s\S]*mask: url\("data:image\/svg\+xml/)
  assert.match(styles, /\.note-tree-group\[data-expanded="true"\] \.tree-folder-icon/)
  assert.match(styles, /\.tree-document-icon \{[\s\S]*mask: url\("data:image\/svg\+xml/)
  assert.match(styles, /\.note-tree-document\[aria-current="page"\] \.tree-document-icon/)
  assert.match(styles, /\.markdown-preview/)
  assert.match(styles, /\.markdown-table-scroll \{[\s\S]*overflow-x: auto/)
  assert.match(styles, /\.note-editor \{[\s\S]*container-name: note-editor;[\s\S]*container-type: inline-size;/)
  assert.match(styles, /\.note-editor-actions \{[\s\S]*flex-wrap: wrap;/)
  assert.match(styles, /@container note-editor \(max-width: 920px\)/)
  assert.match(styles, /@container note-editor \(max-width: 480px\)/)
  assert.match(styles, /@media \(max-width: 1120px\), \(hover: none\) and \(pointer: coarse\) and \(max-width: 1400px\)/)
  assert.match(styles, /\.document-finalized-banner/)
  assert.match(styles, /container-type: inline-size/)
  assert.match(styles, /note-workspace\[data-tree-open="true"\]/)
  assert.match(styles, /\.dialog \{[\s\S]*background: var\(--dialog-surface\)/)
  assert.match(styles, /\.input, \.select \{ height: 38px/)
  assert.match(styles, /scrollbar-color: var\(--scrollbar-thumb\) transparent/)
  assert.match(styles, /--workspace-glass-surface: rgba\(255, 255, 255, 0\.16\)/)
  assert.match(styles, /--material-panel: rgba\(255, 255, 255, 0\.24\)/)
  const designResponse = await fetch(`${base}/knowledge/design-tokens.css`)
  assert.equal(designResponse.status, 200)
  const design = await designResponse.text()
  assert.match(design, /--accent:#3a3a3c/)
  assert.match(design, /@media\(prefers-color-scheme:dark\)[\s\S]*--accent:#69b6ba/)
  assert.match(styles, /--glass-filter: saturate\(1\.22\) contrast\(1\.03\) blur\(32px\)/)
  assert.match(styles, /@media \(prefers-color-scheme: dark\)[\s\S]*:root:not\(\[data-color-scheme\]\)/)
  assert.match(styles, /:root\[data-color-scheme="dark"\]/)
  assert.match(styles, /:root\[data-dsh-embed-mode="embedded"\],[\s\S]*--surface-canvas: transparent/)
  assert.match(styles, /:root\[data-dsh-embed-mode="embedded"\] \{[^}]*--workspace-glass-surface: var\(--knowledge-embedded-surface\);[^}]*--glass-filter: var\(--knowledge-embedded-filter\);/)
  assert.match(styles, /:root\[data-dsh-embed-mode="embedded"\] body,[\s\S]*:root\[data-dsh-host-theme="true"\] body \{ background: transparent; \}/)
  assert.match(application, /class: 'notes-file-columns'/)
  assert.match(application, /noteInfoItem\('格式'/)
  assert.match(styles, /\.notes-file-columns, \.notes-file-row \{/)
  assert.match(styles, /\.notes-file-info \{[^}]*display: grid;/)
  assert.doesNotMatch(styles, /knowledge-card-surface|knowledge-border-surface|knowledge-glare-surface|knowledge-list-reveal|knowledge-animated-list/)
  assert.doesNotMatch(styles, /data-knowledge-glass="svg"|--knowledge-glass-filter/)
  assert.match(styles, /\.note-workspace \{[\s\S]*?background: transparent;[\s\S]*?box-shadow: none;/)
  assert.match(styles, /@media \(prefers-reduced-transparency: reduce\)/)
  assert.match(styles, /input\[type="checkbox"\],[\s\S]*appearance: none;/)
  assert.match(styles, /input\[type="checkbox"\]:checked,[\s\S]*background: var\(--accent\)/)
  assert.match(styles, /\.select \{[\s\S]*appearance: none;[\s\S]*background-image:/)
  assert.match(styles, /\.range-row input\[type="range"\]::-webkit-slider-thumb/)
  assert.match(styles, /\.archived-bases summary::-webkit-details-marker/)
  assert.match(styles, /\.base-grid \{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 390px\), 1fr\)\)/)
  assert.doesNotMatch(styles, /grid-template-columns: subgrid/)
  assert.match(styles, /\.library-detail-header/)
  assert.match(styles, /\.candidate-change/)
  assert.match(styles, /\.diff-viewer \{[^}]*overscroll-behavior: auto;/)
  assert.match(styles, /\.notes-workspace/)
  assert.match(styles, /\.app-shell\[data-view="notes"\] \.main,[\s\S]*?\.app-shell\[data-view="entries"\] \.main \{ height: 100svh; height: 100dvh; min-height: 0; display: grid; grid-template-rows: auto minmax\(0, 1fr\); overflow: hidden; \}/)
  assert.match(styles, /\.notes-workspace \{ height: 100%; min-height: 0; grid-template-columns: minmax\(0, 1fr\); grid-template-rows: minmax\(0, 1fr\); isolation: isolate; \}/)
  assert.match(styles, /\.notes-browser \{[\s\S]*?position: absolute;[\s\S]*?visibility: hidden;/)
  assert.match(styles, /\.notes-browser \{[\s\S]*?position: absolute;[\s\S]*?background: var\(--surface\);[\s\S]*?backdrop-filter: none;/)
  assert.match(styles, /\.note-tree-panel \{[\s\S]*?position: absolute;[\s\S]*?background: var\(--surface\);[\s\S]*?backdrop-filter: none;/)
  assert.match(styles, /\.sidebar \{[\s\S]*?position: fixed;[\s\S]*?background: var\(--surface\);[\s\S]*?backdrop-filter: none;/)
  assert.match(styles, /\.notes-workspace\[data-browser-open="true"\] \.notes-browser/)
  assert.match(styles, /\.notes-browser-scrim \{ position: absolute;/)
  assert.match(styles, /\.notes-file-list \{ min-width: 0; display: grid;/)
  assert.match(styles, /\.notes-file-row \{ min-width: 0; min-height: 0; grid-template-columns: minmax\(0, 1fr\) auto;/)
  assert.match(styles, /\.notes-file-actions \{ grid-column: 1 \/ -1; display: grid;/)
  assert.match(styles, /\.dialog, \.dialog\.narrow, \.dialog\.sheet \{ width: 100%; height: 100svh; height: 100dvh;/)
  assert.match(styles, /font-size: 16px;/)
  assert.match(styles, /env\(safe-area-inset-bottom\)/)
  assert.match(styles, /\.app-shell \{[\s\S]*height: 100dvh;[\s\S]*overflow: hidden;/)
  assert.doesNotMatch(styles, /transition: grid-template-columns/)
  assert.match(styles, /\.route-progress span \{[^}]*transform: scaleX\(var\(--route-progress\)\)/)
  assert.doesNotMatch(styles, /skeleton-shimmer|dialog-backdrop-enter/)
  assert.doesNotMatch(styles, /\.(?:button|base-card|metric|knowledge-card)[^{}]*:hover[^{}]*\{[^}]*transform:/)
  assert.match(styles, /\.sidebar \{[\s\S]*border-radius: 15px;[\s\S]*overflow: hidden;/)
  assert.match(styles, /data-sidebar-hidden="true"\][^}]*> \.sidebar \{[\s\S]*opacity: 0;[\s\S]*translateX/)
  assert.doesNotMatch(styles, /data-sidebar-hidden="true"[^}]*\{[^}]*display: none/)
  assert.match(styles, /\.nav \{[\s\S]*overflow-x: hidden;[\s\S]*overflow-y: auto;[\s\S]*scrollbar-gutter: stable;/)
  assert.doesNotMatch(styles, /\.nav-button:hover \{[^}]*translateX/)
  assert.match(styles, /\.topbar \{[\s\S]*border-radius: 0;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.main \{[\s\S]*height: calc\(100dvh - var\(--chrome-inset\) \* 2\);[\s\S]*overflow-y: auto;/)
  assert.match(styles, /\.app-shell\[data-view="notes"\] \.view-stage \{[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(design, /--font-reading:/)
  assert.match(styles, /\.markdown-preview \{[\s\S]*font: 16px\/1\.55 var\(--font-reading\);/)
  assert.match(styles, /\.notes-tree-branch\[role="group"\]/)
  assert.match(styles, /\.notes-tree-chevron::before/)
  assert.match(styles, /\.notes-file-info/)
  assert.match(styles, /\.notes-live-editor-surface/)
  assert.match(styles, /\.notes-editor-outline/)
  assert.match(styles, /\.notes-find-panel/)
  assert.match(styles, /\.notes-selection-menu/)
  assert.match(styles, /\.note-history-workspace/)
  assert.match(styles, /\.notes-document-more-menu/)
  assert.match(styles, /\.notes-document-more > summary \{[^}]*display: inline-grid;[^}]*color: var\(--text\);/)
  assert.match(styles, /\.notes-document-more-menu \.button \{[^}]*grid-template-columns: 20px minmax\(0, 1fr\);[^}]*text-align: left;/)
  assert.match(styles, /\.notes-document-menu-icon/)
  assert.doesNotMatch(styles, /data-note-mobile-overflow/)
  assert.match(styles, /\.notes-save-state \{ display: inline-flex; min-height: 44px;/)
  assert.match(styles, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
  assert.doesNotMatch(styles, /\.notes-document-toolbar \{ align-items: center; flex-direction: row; overflow-x: auto; \}/)
  assert.match(styles, /\.notes-content\.is-document \{ --notes-document-inline: 16px; \}/)
  assert.match(styles, /\.notes-live-editor-surface \.tableWrapper \{ width: 100%; max-width: 100%; overflow-x: auto;/)
  assert.match(styles, /\.knowledge-live-editor/)
  assert.doesNotMatch(styles, /\.note-mode-switch/)
  assert.doesNotMatch(styles, /\.notes-document-paper/)
  assert.doesNotMatch(styles, /\.notes-document-editor/)
  assert.match(styles, /\.notes-document-title/)
  assert.match(styles, /\.notes-document-title:focus,[\s\S]*box-shadow: none;/)
  assert.match(styles, /\.notes-plain-editor \{[\s\S]*background: transparent;/)
  assert.match(styles, /\.notes-plain-editor-surface \{[\s\S]*counter-reset: note-line;[\s\S]*cursor: text;/)
  assert.match(styles, /\.notes-plain-editor-surface > p::before \{[\s\S]*content: counter\(note-line\);[\s\S]*user-select: none;/)
  assert.doesNotMatch(styles, /\.notes-plain-editor \.cm-/)
  assert.match(styles, /\.notes-content\.is-document\.has-line-numbers \{[\s\S]*--notes-document-inline:/)
  assert.match(styles, /\.notes-content\.is-document \{[\s\S]*display: block;/)
  assert.match(styles, /\.notes-tree-branch \{[\s\S]*grid-template-columns: minmax\(0, 1fr\);/)
  assert.match(styles, /\.notes-tree-node \{[\s\S]*min-width: 0;[\s\S]*max-width: 100%;/)
  assert.match(styles, /\.notes-tree-row \{[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.notes-tree-name \{[\s\S]*text-overflow: ellipsis;/)
  assert.match(styles, /\.notes-tree-item:hover \.notes-tree-row,[\s\S]*padding-right: calc\(var\(--notes-row-actions-width\) \+ 7px\);/)
  assert.match(styles, /\.notes-live-editor-surface:focus,[\s\S]*box-shadow: none;/)
  assert.match(styles, /\.notes-inline-viewer/)
  assert.match(styles, /\.note-reference/)
  assert.match(styles, /\.document-reference-bar/)
  assert.match(styles, /\.document-reference-list \{[\s\S]*overflow-x: auto/)
  assert.match(styles, /\.notes-drop-overlay/)
  assert.match(styles, /\.notes-transfer-track/)
  assert.match(styles, /transform: scaleX\(var\(--notes-transfer-progress\)\)/)
  assert.match(styles, /\.notes-transfer\[data-state="scanning"\] \.notes-transfer-fill/)
  assert.match(styles, /\.diff-line\.is-add/)
  assert.match(styles, /\.diff-line\.is-remove/)
  assert.match(styles, /\.diff-viewer/)
  assert.match(styles, /\.bulk-review-status/)
  assert.match(styles, /\.bulk-review-metrics/)
  assert.doesNotMatch(styles, /candidate-comparison/)
  assert.match(styles, /\[data-base-detail="true"\]/)
  const shellSource = application.slice(application.indexOf('function renderShell()'), application.indexOf('function renderSidebar()'))
  assert.doesNotMatch(shellSource, /新建知识库|新建知识/)
  const sidebarSource = application.slice(application.indexOf('function renderSidebar()'), application.indexOf('function renderCurrentView()'))
  assert.match(sidebarSource, /知识工作区/)
  assert.match(sidebarSource, /笔记工作区/)
  assert.match(sidebarSource, /知识库与挂载/)
  assert.doesNotMatch(sidebarSource, /interfaceIcon|nav-icon/)
  const documentsSource = application.slice(application.indexOf('function renderEntries()'), application.indexOf('function renderCandidates()'))
  assert.match(documentsSource, /note-tree-search/)
  assert.match(documentsSource, /新建文档/)
  assert.match(documentsSource, /KNOWLEDGE_DOCUMENT_DRAG_TYPE/)
  assert.match(application, /getData\(KNOWLEDGE_DOCUMENT_DRAG_TYPE\)/)
  assert.match(documentsSource, /移动到…/)
  assert.match(documentsSource, /activateKnowledgeBaseDropTarget/)
  assert.doesNotMatch(documentsSource, /条目管理/)
  const knowledgeBaseCardSource = application.slice(application.indexOf('function renderKnowledgeBaseCard('), application.indexOf('function findExplicitMount('))
  assert.match(knowledgeBaseCardSource, /查看知识/)
  assert.match(knowledgeBaseCardSource, /openKnowledgeBaseDocuments/)
  assert.doesNotMatch(knowledgeBaseCardSource, /navigate\('entries'\)/)
  assert.match(application, /function openSheet/)
  assert.match(styles, /dialog\.sheet/)

  const apiClientResponse = await fetch(`${base}/knowledge/api-client.js`)
  assert.equal(apiClientResponse.status, 200)
  assert.match(apiClientResponse.headers.get('content-type'), /text\/javascript/)
  const apiClient = await apiClientResponse.text()
  assert.match(apiClient, /function binaryUploadRequest\(/)
  assert.match(apiClient, /request\.upload\.addEventListener\('progress'/)

  for (const moduleName of ['host-theme.js', 'ui-primitives.js', 'model-catalog.js', 'dialogs.js', 'select-control.js']) {
    const response = await fetch(`${base}/knowledge/${moduleName}`)
    assert.equal(response.status, 200)
    assert.match(response.headers.get('content-type'), /text\/javascript/)
    if (moduleName === 'ui-primitives.js') {
      const primitives = await response.text()
      assert.match(primitives, /createElementNS\('http:\/\/www\.w3\.org\/2000\/svg'/)
      assert.match(primitives, /vectorElement\('path'/)
    }
  }

  const markdownPreview = await fetch(`${base}/knowledge/markdown-preview.js`)
  assert.equal(markdownPreview.status, 200)
  assert.match(markdownPreview.headers.get('content-type'), /text\/javascript/)
  assert.equal(markdownPreview.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  assert.match(await markdownPreview.text(), /DshKnowledgeMarkdown/)

  const noteEditor = await fetch(`${base}/knowledge/note-editor.js`)
  assert.equal(noteEditor.status, 200)
  assert.match(noteEditor.headers.get('content-type'), /text\/javascript/)
  assert.equal(noteEditor.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  const noteEditorSource = await noteEditor.text()
  assert.match(noteEditorSource, /DshKnowledgeNoteEditor/)
  assert.match(noteEditorSource, /spellcheck:"false"/)
  assert.match(noteEditorSource, /notes-search-result-current/)
  assert.match(noteEditorSource, /notes-editor-outline-header/)
  assert.match(noteEditorSource, /\.scrollTo\(\{top:/)
  assert.doesNotMatch(noteEditorSource, /element\?\.scrollIntoView/)
  assert.match(noteEditorSource, /notes-selection-primary/)
  assert.match(noteEditorSource, /pointerup/)
  assert.match(noteEditorSource, /pointercancel/)

  const noteHistory = await fetch(`${base}/knowledge/note-history.js`)
  const excerptModule = await fetch(`${base}/knowledge/note-excerpt.js`)
  assert.equal(excerptModule.status, 200)
  assert.match(await excerptModule.text(), /export async function openNoteExcerpt/)
  assert.equal(noteHistory.status, 200)
  assert.match(noteHistory.headers.get('content-type'), /text\/javascript/)
  assert.equal(noteHistory.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  assert.match(await noteHistory.text(), /DshKnowledgeNoteHistory/)

  const plainTextEditor = await fetch(`${base}/knowledge/plain-text-editor.js`)
  assert.equal(plainTextEditor.status, 404)

  const changeReview = await fetch(`${base}/knowledge/change-review.js`)
  assert.equal(changeReview.status, 200)
  assert.match(changeReview.headers.get('content-type'), /text\/javascript/)
  assert.equal(changeReview.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  assert.match(await changeReview.text(), /DshKnowledgeReview/)

  const embedded = await fetch(`${base}/knowledge?embed=desktop-embed-token`)
  assert.equal(embedded.status, 200)
  assert.equal(embedded.headers.get('x-frame-options'), null)
  assert.doesNotMatch(embedded.headers.get('content-security-policy'), /frame-ancestors/)
  assert.match(await embedded.text(), /data-dsh-embed-mode="embedded"/)

  const invalidEmbed = await fetch(`${base}/knowledge?embed=wrong-token`)
  assert.equal(invalidEmbed.status, 200)
  assert.equal(invalidEmbed.headers.get('x-frame-options'), 'SAMEORIGIN')
  assert.match(invalidEmbed.headers.get('content-security-policy'), /frame-ancestors 'self'/)
  assert.match(await invalidEmbed.text(), /data-dsh-embed-mode="standalone"/)

  const missing = await fetch(`${base}/knowledge/not-found.js`)
  assert.equal(missing.status, 404)
  const post = await fetch(`${base}/knowledge`, { method: 'POST' })
  assert.equal(post.status, 405)
})
